/**
 * k6 load-test emitter (Phase 4, generate-only).
 *
 * Turns the API endpoint catalog into a runnable k6 script the team executes
 * themselves — so AAQUA has NO load-testing runtime dependency. Mirrors the
 * "you own the output" pattern of the Playwright/REST Assured emitters.
 *
 * Input: { info: { title, serverUrl }, endpoints: [{ method, path, ... }] }
 * Output: { 'load-test.js': ..., 'README.md': ... }
 */

const K6_FN = { GET: 'get', POST: 'post', PUT: 'put', PATCH: 'patch', DELETE: 'del', HEAD: 'head', OPTIONS: 'options' };

// Replace {param} path placeholders with a sample value the user can edit.
function substitute(path) {
    return String(path || '/').replace(/\{[^}]+\}/g, '1');
}

export function emitK6({ info = {}, endpoints = [] }) {
    const serverUrl = info.serverUrl || 'https://api.example.com';

    const blocks = endpoints.map(ep => {
        const method = String(ep.method || 'GET').toUpperCase();
        const fn = K6_FN[method] || 'get';
        const path = substitute(ep.path);
        const checkKey = JSON.stringify(`${method} ${ep.path || '/'} < 400`);
        const hasBody = ['POST', 'PUT', 'PATCH'].includes(method);
        if (hasBody) {
            return `  {
    const payload = JSON.stringify({}); // TODO: realistic request body
    const res = http.${fn}(\`\${BASE_URL}${path}\`, payload, { headers: { 'Content-Type': 'application/json', ...authHeaders } });
    check(res, { ${checkKey}: (r) => r.status < 400 });
  }`;
        }
        return `  {
    const res = http.${fn}(\`\${BASE_URL}${path}\`, { headers: { ...authHeaders } });
    check(res, { ${checkKey}: (r) => r.status < 400 });
  }`;
    }).join('\n');

    const script = `import http from 'k6/http';
import { check, sleep } from 'k6';

// Generated by AAQUA from your API catalog. Review payloads / path params (TODOs)
// below, then run with k6. Load tests are protocol-level (latency/throughput) —
// they do NOT render pages (use the Performance Scanner for Core Web Vitals).
const BASE_URL = __ENV.BASE_URL || ${JSON.stringify(serverUrl)};
const TOKEN = __ENV.API_TOKEN || '';
const authHeaders = TOKEN ? { Authorization: \`Bearer \${TOKEN}\` } : {};

export const options = {
  vus: Number(__ENV.VUS || 10),
  duration: __ENV.DURATION || '30s',
  thresholds: {
    http_req_failed: ['rate<0.01'],      // < 1% of requests may error
    http_req_duration: ['p(95)<800'],    // 95% of requests under 800 ms
  },
};

export default function () {
${blocks}
  sleep(1);
}
`;

    const readme = `# ${info.title || 'API'} — k6 Load Test (generated by AAQUA)

AAQUA generated this script from your API endpoint catalog (generate-only — you
run it yourself, so there's no load-testing dependency inside AAQUA).

## 1. Install k6
- macOS: \`brew install k6\`
- Windows: \`choco install k6\` (or grab the binary from https://k6.io)
- Linux: https://k6.io/docs/get-started/installation/

## 2. Review the script
Open \`load-test.js\` and fill in the \`TODO: realistic request body\` payloads and
any path parameters (placeholders default to \`1\`).

## 3. Run
\`\`\`bash
k6 run -e BASE_URL=${serverUrl} -e API_TOKEN=<token> -e VUS=20 -e DURATION=1m load-test.js
\`\`\`
- \`VUS\` — concurrent virtual users (default 10)
- \`DURATION\` — test length (default 30s)
- Thresholds (in \`options\`): < 1% errors and p95 latency < 800 ms — tune to your SLOs.

k6 prints p90/p95/p99 latency, throughput, and error rate when the run finishes.

> ⚠️ Run load tests against TEST/staging environments only — never production.
`;

    return { 'load-test.js': script, 'README.md': readme };
}
