const fs = require('fs');
let code = fs.readFileSync('server/index.js', 'utf8');
const oldCodeRegex = /const genAI = new GoogleGenerativeAI\(apiKey\);\s*const model = genAI\.getGenerativeModel\(\{ model: "gemini-2\.5-flash" \}\);/g;
const newCode = `const endpoint = process.env.VITE_LLM_ENDPOINT || 'https://llm.lab.aaseya.com/v1';
        const llmModel = process.env.VITE_LLM_MODEL || 'gpt-oss-20b';
        const genAI = new GoogleGenerativeAI(apiKey, endpoint);
        const model = genAI.getGenerativeModel({ model: llmModel });`;
code = code.replace(oldCodeRegex, newCode);
fs.writeFileSync('server/index.js', code, 'utf8');
console.log('Fixed LLM model generation endpoints seamlessly.');
